name: Merge remove-desktop-ini subtree

on:
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      
      - name: Configure git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Fetch subtree branch
        run: git fetch origin remove-desktop-ini

      - name: Merge subtree
        run: |
          git subtree merge --prefix=remove-desktop-ini origin/remove-desktop-ini -m "Merge remove-desktop-ini subtree"

      - name: Push changes
        run: git push origin HEAD:main
