---
name: Sync remove-desktop-ini branch from main

'on':
  workflow_dispatch: {}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure main branch
        run: |
          if [[ "${GITHUB_REF}" != "refs/heads/main" ]]; then
            echo "This workflow must be run on main." >&2
            exit 1
          fi
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - name: Configure git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Push subtree branch
        run: |
          git fetch origin remove-desktop-ini || true
          git subtree push --prefix=remove-desktop-ini origin remove-desktop-ini
